# Uncomment the following line to use OpenMP 2.0 features
#OMPFLAG = -fopenmp
# Uncomment the following line to use OpenMP 3.0 features
OMPFLAG = -fopenmp

CC=gcc-7
CFLAGS =  -O1 -lm
LDFLAGS = -O0 -lm
CPP = /usr/local/bin/g++-7
LIBS = 
